### ISSUE TITLE
odd "hybrid" behavior on macOS/Safari

### ISSUE THREAD

**Issue by dylanmc** [DavidBuchanan314/ambiguous-png-packer#1]
In Safari 15.1 on macOS 10.15.7, I'm seeing "Hello Apple", but the picture is of the PC.

![Screen Shot 2021-12-16 at 11 14 34 AM](https://user-images.githubusercontent.com/768946/146434138-85c2b5b8-d6c2-41fc-8824-bbc32033eb7d.png)

**Comment by dylanmc** [comment]
Browser "Force reload" changed the behavior to seeing the macintosh on the demo page, but not on the github project page.

**Comment by dylanmc** [comment]
I see you've noted this odd / race behavior in the writeup. Issue closed.

**Comment by DavidBuchanan314** [comment]
To be honest, I don't fully understand why the race is there, I'd love to know the root cause.
