### ISSUE TITLE
Replication

### ISSUE THREAD

**Issue by ThisOne5022** [DavidBuchanan314/ambiguous-png-packer#4]
I was wondering how I can replicate this with different reference images. Do I need to modify the python code in any way to match the images?

**Comment by AGaiki** [comment]
Not sure if related, but attempting to run the script on both macOS and Windows (Python 3.10.0) results in a `ModuleNotFoundError` (`ModuleNotFoundError: No module named 'PIL'`). Attempting to install it using pip results in `ERROR: No matching distribution found for PIL`.

**Comment by maxicarlos08** [comment]
You are missing the Pillow python package, install it by running:

```
pip install Pillow
```

**NOTE**: [Pillow](https://python-pillow.org/) is the successor of [PIL](https://web.archive.org/web/20201121102218/http://www.pythonware.com/products/pil/) (Python image library), which can also be imported using PIL

**Comment by ThisOne5022** [comment]
That worked. Thank you!
