### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ghost** [DavidBuchanan314/ambiguous-png-packer#6]
Can anyone please give me link to any tutorial of how to use it?
Thanks

**Comment by MrMysterius** [comment]
I'm not sure but I found this.

![image](https://user-images.githubusercontent.com/25854814/147006056-f92694fd-0f74-44f5-b518-382b2e3c3d85.png)

It seems you run the script from command line and the first argument is the PNG that apple software users will see, then the images others will see and then the name/file to save the newly made/altered image to.

```
python3 pack.py <PNG Input Filename for Apple Users> <PNG Input Filename for Other Users> <PNG Output Filename>
```

**Comment by ghost** [comment]
> I'm not sure but I found this.
> 
> ![image](https://user-images.githubusercontent.com/25854814/147006056-f92694fd-0f74-44f5-b518-382b2e3c3d85.png)
> 
> It seems you run the script from command line and the first argument is the PNG that apple software users will see, then the images others will see and then the name/file to save the newly made/altered image to.
> 
> ```
> python3 pack.py <PNG Input Filename for Apple Users> <PNG Input Filename for Other Users> <PNG Output Filename>
> ```

It works, TYSM!
